--------------------------------------------------------
-- Archivo creado  - jueves-agosto-24-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "SISTEMASDB"."LOGIN" 
   (	"USUARIO" VARCHAR2(200 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"NOMBRE" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"ROLUSER" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"FECHAALTA" DATE DEFAULT NULL, 
	"SWACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"SWMODPASS" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"SWMODIFICAR" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"URL" VARCHAR2(100 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SISTEMASDB.LOGIN
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index SYS_C007018
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMASDB"."SYS_C007018" ON "SISTEMASDB"."LOGIN" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "SISTEMASDB"."LOGIN" ADD PRIMARY KEY ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SISTEMASDB"."LOGIN" MODIFY ("USUARIO" NOT NULL ENABLE);

------------------------------------------------------------------------
--  Creación del usuario ADMIN para poder acceder a la aplicación
------------------------------------------------------------------------

Insert into SISTEMASDB.LOGIN (USUARIO,PASSWORD,NOMBRE,ROLUSER,FECHAALTA,SWACTIVO,SWMODPASS,SWMODIFICAR,URL) 
values ('ADMIN','21232f297a57a5a743894a0e4a801fc3','Administrador','ROLE_ADMIN',to_date(SYSDATE,'DD/MM/RR'),'S','S','N',null);
