--------------------------------------------------------
-- Archivo creado  - jueves-agosto-24-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DELEGACION
--------------------------------------------------------

  CREATE TABLE "SISTEMASDB"."DELEGACION" 
   (	"DEL_CODIGO" VARCHAR2(3 BYTE), 
	"DEL_NOMBRE" VARCHAR2(60 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SISTEMASDB.DELEGACION
SET DEFINE OFF;
Insert into SISTEMASDB.DELEGACION (DEL_CODIGO,DEL_NOMBRE) values ('AND','Andalucía');
Insert into SISTEMASDB.DELEGACION (DEL_CODIGO,DEL_NOMBRE) values ('CAN','Canarias');
Insert into SISTEMASDB.DELEGACION (DEL_CODIGO,DEL_NOMBRE) values ('CAT','Cataluña');
Insert into SISTEMASDB.DELEGACION (DEL_CODIGO,DEL_NOMBRE) values ('LEV','Levante');
Insert into SISTEMASDB.DELEGACION (DEL_CODIGO,DEL_NOMBRE) values ('CTR','Central (Sistemas)');
Insert into SISTEMASDB.DELEGACION (DEL_CODIGO,DEL_NOMBRE) values ('BAL','Baleares');
--------------------------------------------------------
--  DDL for Index SYS_C007060
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMASDB"."SYS_C007060" ON "SISTEMASDB"."DELEGACION" ("DEL_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DELEGACION
--------------------------------------------------------

  ALTER TABLE "SISTEMASDB"."DELEGACION" ADD PRIMARY KEY ("DEL_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SISTEMASDB"."DELEGACION" MODIFY ("DEL_CODIGO" NOT NULL ENABLE);
